# GET http://localhost:8080/monitor/liveness

# POST http://localhost:8080/user
# Content-Type: application/json; charset=UTF-8

# {
#   "name": "blue",
#   "email": "blue@gmail.com",
#   "password": "blue1234"
# }

POST http://localhost:8080/post
Content-Type: application/json; charset=UTF-8

{
  "authorId": 2,
  "title": "title",
  "content": "content",
  "isPublished": false
}