app:
  name: your-app
  port: 8080
  env: "staging"

database:
  dialect: mysql
  username: youruser
  password: yourpassword
  host: localhost
  port: 3306
  name: yourdb
  charset: utf8mb4
  parseTime: true
